<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->appendStylesheet($this->basePath() . '/css/bootstrap.css')
                        ->appendStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->appendStylesheet($this->basePath() . '/modules/dev-ctrl/css/style.css') ?>

        <!-- vendor scripts -->
        <?php
            echo $this->ctrlJsLoader()->loadScripts(true);
        ?>
        <!-- Custom Scripts -->
        <?php echo $this->headScript()->appendFile($this->basePath() . '/js/init.js'); ?>
    </head>
    <body>

    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
            <a class="brand" href="<?php echo $this->url('default') ?>"><?php echo $this->translate('Ctrl Framework') ?></a>
            <?php echo $this->navigation()->menu($this->navigation['main'])->renderMenu(null, array('maxDepth' => 0)); ?>
            </div>
        </div>
        <div class="navbar-inner">
            <div class="container">
                <?php echo $this->navigation()->menu($this->navigation['main'])->setOnlyActiveBranch(true)->renderMenu(null, array('minDepth' => 1, 'maxDepth' => 1)); ?>
            </div>
        </div>
    </div>

    <br />

    <div class="container">
        <?php echo $this->render('app/partial/app-messages.phtml'); ?>
    <?php echo $this->content; ?>

    <hr>

    <footer>
        <p>&copy; 0.0.0 development</p>
    </footer>

    </div>

    </body>
</html>
