<?php echo $this->pageTitle('Welcome, browse our catalog'); ?>

<table class="table">
    <thead>
    <tr>
        <th>Company</th>
        <th>Catalog Dates</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    <?php
    /** @var $company \App\Domain\Company */
    foreach ($companies as $company) : ?>
        <tr>
            <td><?php echo $company->getName(); ?></td>
            <td><?php $range = $company->getCatalogDateRange(); echo $range['oldest'].' - '.$range['newest']; ?></td>
            <td><?php echo $this->ctrlButton('link', array(
                'url' => $this->url('default/default', array(
                    'controller' => 'car',
                    'action' => 'index',
                    'company' => $company->getId(),
                )),
                'value' => 'view cars',
            ), 'info'); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
